name: build ruleset

on:
  workflow_dispatch:
    inputs:
      packages:
        description: 'Release description or package info'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install sing-box
        run: curl -fsSL https://sing-box.app/install.sh | sh

      - name: Build ruleset
        run: |
          cd $GITHUB_WORKSPACE
          wget -q https://gist.githubusercontent.com/wbmins/ae0a36e31e7efdf5f06d262d89c3b68c/raw/reject.json
          cat ./reject.json
          sing-box rule-set compile --output reject.srs ./reject.json

      - name: Upload and Overwrite Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.workspace }}/reject.srs
            ${{ github.workspace }}/reject.mrs
          tag_name: latest
          overwrite: true
          body: ${{ github.event.inputs.packages }}
